# Use postgres/example user/password credentials
version: '3.1'
services:
  PostgresDB:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: VeryStrongPassword123ForBD
    ports:
      - 5432:34652
    volumes:
    - ./:/docker-entrypoint-initdb.d